### ISSUE TITLE
Rename dataloaders

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoiseq#13]
- `datasets.py` -> `dataloaders.py`
- `SeqDataset` -> `IntervalSeqDl`
- `SpliceDataset` -> `MMSpliceDl`

In the future, we will also have:
- `IntervalSeqVariantDl`
- `MMSpliceVariantDl`

If possible, use only a single dataloader to do both, one-hot-encoding and string output:
- this would require to modify the dataloader schema
  - we should have a class method for each dataloader to change the schema accordingly

@s6juncheng @gagneur @krrome What's your opinion?

**Comment by krrome** [comment]
I would call them `SeqIntervalDl`and `SeqIntervalVariantDl`.

> If possible, use only a single dataloader to do both, one-hot-encoding and string output:

I don't think it is necessary at this stage to spend more time on fine-tuning the dataloader classes. I don't see an improvement for the user or the maintainer and it requires implementation time we very much lack in other core issues

**Comment by Avsecz** [comment]
I will call it `IntervalSeqDl` since it's a interval sequence and not a sequence interval. And for the variant we can call it `VariantSeqDl` since it's the sequence around the variant.

**Comment by Avsecz** [comment]
Ok. "Interval Sequence` could be confused as a sequence of intervals. Will call them:
- `SeqIntervalDl`
- `StringSeqIntervalDl`
- `SeqVariantDl`
- `StringSeqVariantDl`
