### ISSUE TITLE
Drop python 3.5?

### ISSUE THREAD

**Issue by Hoeze** [kipoi/kipoiseq#58]
Python 3.5 does not support type annotations and format strings.
@Avsecz @MuhammedHasan Should we drop python 3.5 support in the near future or is this still a requirement for some Kipoi models?

**Comment by Avsecz** [comment]
Python 3.5 supports type annotations: https://docs.python.org/3.5/library/typing.html

I would keep 3.5 for now. Format strings are a nice syntactic sugar, but are not a good enough reason to drop 3.5.

**Comment by MuhammedHasan** [comment]
I agree with @Avsecz. People still use 3.5 so it will be annoying to drop version.

**Comment by Hoeze** [comment]
> Python 3.5 supports type annotations: https://docs.python.org/3.5/library/typing.html

Yes, but only in parts.
Not working:
```python3
class BaseVariantMatcher:
    """
    Base variant intervals matcher
    """

    def __init__(
            self,
            vcf_file: str,
            gtf_path: str = None,
            bed_path: str = None,
            pranges: pyranges.PyRanges = None,
            intervals: List[Interval] = None,
            interval_attrs: List[str] = None,
            vcf_lazy: bool = True,
            variant_batch_size: int = 10000
    ):
        [...]
```
